language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.8

sudo: false

compiler:
  - gcc

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export CMAKE="cmake-3.3.0-Linux-x86_64"
      && $CMAKE/bin/cmake .
      ;
    fi

script:
  - make
    && find . -maxdepth 1 -type f -perm -001 -exec {} \;
    && echo $?
    ;

branches:
  only:
    - master

env:
  - LANG="en_US.UTF-8"

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      CMAKE="cmake-3.3.0-Linux-x86_64"
      && curl -o $CMAKE.sh http://www.cmake.org/files/v3.3/$CMAKE.sh
      && sh $CMAKE.sh --skip-license --include-subdir
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    fi

os:
  - linux
